version: '3.6'
services:
  minio:
    container_name: s3.6
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    environment:
      - MINIO_ROOT_USER=insert-user-name
      - MINIO_ROOT_PASSWORD=insert-password
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
  # configure minio on startup (create buckets, etc)
  # inspired by https://github.com/minio/minio/issues/4769
  # and         https://gist.github.com/haxoza/22afe7cc4a9da7e8bdc09aad393a99cc
  minio_init:
    container_name: s3.6_init
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 insert-user-name insert-password;
      /usr/bin/mc mb minio/project-data;
      /usr/bin/mc anonymous set public minio/project-data;
      /usr/bin/mc cp --recursive /models/ minio/project-data/model-library/;
      /usr/bin/mc rb --force  minio/ccstore;
      /usr/bin/mc mb minio/ccstore;
      /usr/bin/mc anonymous set public minio/ccstore;
      exit 0;
      "
    volumes:
      - ../data:/models